# Site settings
title: "Athénée"
email: hello@mail.io
description: ""
url: "https://thebig-o.github.io/"
baseurl: "/athenee-MFO"
flickr_username: "m_olness"

# Owner/author information
owner:
  name:   "Athénée"
  avatar: ""
  favicon: favicon.ico

# Internal nav
nav:
 Animals: "baseurl/gallery1/"
 HDRs: "baseurl/gallery2/"
 Landscapes: "baseurl/gallery3/"
 Sunsets: "baseurl/gallery4/"
 Buildings: "baseurl/gallery5/"
 about: "baseurl/about/"

# Server
destination:      	 ./_site
port:             	 4000

# Build settings
markdown: kramdown
highlighter: pygments
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
